# Generated by Django 5.2.5 on 2025-08-07 23:47

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='nombre')),
                ('foto', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categoria')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'db_table': 'blogs',
            },
        ),
    ]
